-- sql/V1__Initialize_analytics_schema.sql

-- 1. Create the schema (equivalent to an Oracle user namespace)
CREATE SCHEMA IF NOT EXISTS analytics;

-- 2. Create the target table
CREATE TABLE analytics.var_x (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prog_1 NUMERIC
);

-- 3. Create the source table
CREATE TABLE analytics.source_table (
    datum DATE,
    kuendiger INT
);

-- 4. Insert dummy data
INSERT INTO analytics.source_table (datum, kuendiger) VALUES ('2026-04-01', 30);
INSERT INTO analytics.source_table (datum, kuendiger) VALUES ('2026-04-02', 34);
INSERT INTO analytics.source_table (datum, kuendiger) VALUES ('2026-04-03', 45);
INSERT INTO analytics.source_table (datum, kuendiger) VALUES ('2026-04-04', 38);
INSERT INTO analytics.source_table (datum, kuendiger) VALUES ('2026-04-05', 41);

-- Note: Flyway wraps migrations in a transaction automatically, so an explicit COMMIT is not needed.
